### ISSUE TITLE
[BUG] Board members avatar size

### ISSUE THREAD

**Issue by miguel-felix1** [xgeekshq/split#1012]
## Description
As a user I should be able to easily identify board members

### Current behavior
Text on the user's avatar is too big, should be size 12 instead of 16

Current
![Image](https://user-images.githubusercontent.com/87712174/216625705-73e1ab3a-5994-44e7-a566-7529dd5952f3.png)
Fix
![Image](https://user-images.githubusercontent.com/87712174/216625867-ea5e5dd5-1e63-44a5-be58-27b0a3e9160d.png)

**Comment by StereoPT** [comment]
Fixed after #998 🗝️
