### ISSUE TITLE
[BUG]: Content of all boards is being exposed 

### ISSUE THREAD

**Issue by dvpfran** [xgeekshq/split#1014]
## Description

At the moment, the main board of January has all cards content hidden and if we try to inspect the element, we see this "aaaa":  

![Screenshot 2023-02-03 at 15 13 27](https://user-images.githubusercontent.com/67462841/216638602-9dc88105-061c-4041-a9da-70441c7888a9.png)  

But if we go to the Network tab and check the response request, we can see the content of all cards:  

![Screenshot 2023-02-03 at 15 15 37](https://user-images.githubusercontent.com/67462841/216639093-bf73efa7-ad7a-4992-add2-0d00cbd87772.png)

Another issue, the sub-teams that are not merged to mainboard, it's possible to see their content cards. The example bellow is from team 3:

![Screenshot 2023-02-03 at 15 16 53](https://user-images.githubusercontent.com/67462841/216639338-f6e27be9-0ed5-4091-833a-043840b21a37.png)

### Steps to reproduce

1 - Open the network tab and refresh the main page
2 - Check the response of GET https://split-be.azurewebsites.net/boards/63da7ea1f1ffb3f94d1ad30f
![Screenshot 2023-02-03 at 15 24 06](https://user-images.githubusercontent.com/67462841/216640967-f2be69a2-9c26-422d-928b-7fef6dd64fc6.png)

3 - Check the board.dividedBoards variable and you will see all the information
![Screenshot 2023-02-03 at 15 24 35](https://user-images.githubusercontent.com/67462841/216641065-352fe0f7-f3c4-4989-a202-de43f0c5cf05.png)

### Expected result

What should happen?
This information should not be exposed

**Comment by nunocaseiro** [comment]
Nice catch! Thank you for your feedback we will fix this in a few minutes
