### ISSUE TITLE
[BUG] Column max name

### ISSUE THREAD

**Issue by miguel-felix1** [xgeekshq/split#1092]
## Description
As a user I should be able to create a column in a regular board

### Current behavior
Column max length displays as 30 but field doesn't allow for more than 15

![Image](https://user-images.githubusercontent.com/87712174/219348446-27b93633-7978-4a8b-9251-5d298e166ba3.png)

**Comment by JoaoSaIvador** [comment]
This issue is already fixed with the pr #1094
