### ISSUE TITLE
[BUG]: save button not displayed

### ISSUE THREAD

**Issue by CatiaAntunes96** [xgeekshq/split#1241]
## Description

When a user tries do edit the board configurations on a split or regular board, there isn't a button to save the changes.

### Steps to reproduce

Edit a configuration or name of a board.

### Expected result

A button to save the changes should be displayed.

### Actual result

Only the Cancel button is displayed.

**Comment by JoaoSaIvador** [comment]
This issue was solved with the pr #1244
