### ISSUE TITLE
[BUG]: Search bar cursor position

### ISSUE THREAD

**Issue by nunocaseiro** [xgeekshq/split#1347]
## Description

The cursor position of the search input isn't in the right place when the placeholder moves up

### Actual result

![Screenshot 2023-04-04 at 10 39 12](https://user-images.githubusercontent.com/90208434/229752769-ffde940e-af06-41ec-bf06-750545ad53ef.png)

**Comment by JoaoSaIvador** [comment]
The solution to this issue will already be included in the pr of the issue #1332
