### ISSUE TITLE
[BUG]: Incorrect RETRO Documentation

### ISSUE THREAD

**Issue by jpjcorreia** [xgeekshq/split#1514]
## Description

When the bot creates the monthly slack message, with all the sub-teams and responsibles, the link to the RETRO documentation is pointing to the old confluence pages.

### Steps to reproduce

Click on the link to the docs at the bottom of the slack message:
![CleanShot 2023-11-24 at 11 22 12@2x](https://github.com/xgeekshq/split/assets/28530831/5afe1c7d-a901-466f-b367-f1577872bb5a)

### Expected result

What should happen?
The link should point to the new confluence location: https://kigroup.atlassian.net/wiki/spaces/OX/pages/416055630/Retro

### Actual result

The link points to the old confluence space.

**Comment by nunocaseiro** [comment]
@jpjcorreia thank you for your feedback. I'll update it asap
