### ISSUE TITLE
[FEATURE]: Create Board Settings

### ISSUE THREAD

**Issue by f-morgado** [xgeekshq/split#223]
## Summary

Create Board Settings in order to do toggle the settings for the boards creation

### User story it relates to
#144 

### Motivation
Giving the liberty for stakeholders to be able to change the settings accordingly to what is needed/requested.

**Comment by dsousa12** [comment]
### Suggestions:
- [ ] Use [**Radix Dialog**](https://www.radix-ui.com/docs/primitives/components/dialog) with custom styles
   - This way you already have the "press ESC" to close, click on overlay to close and other accessability things
- [ ] Create separated issues for "Hide Votes from others" and "Post Cards Anonymously"
