### ISSUE TITLE
[FIX]: Avatar color 

### ISSUE THREAD

**Issue by dvpfran** [xgeekshq/split#260]
## Summary
The avatar color are always changing.

### Basic example
First reload:
<img width="1121" alt="Screenshot 2022-06-24 at 17 14 01" src="https://user-images.githubusercontent.com/67462841/175577087-2d8ad7b5-cf5c-4f61-808c-89af546bfc28.png">

Second reload:
<img width="1123" alt="Screenshot 2022-06-24 at 17 14 52" src="https://user-images.githubusercontent.com/67462841/175577165-ec4016f4-16b7-45e2-9a08-0bbed17a10fc.png">

Third reload: 
<img width="1119" alt="Screenshot 2022-06-24 at 17 15 29" src="https://user-images.githubusercontent.com/67462841/175577240-de1a3849-cd39-4c13-8e5c-b1200a4c3c3e.png">

# Motivation 
Don't confuse users.

**Comment by nunocaseiro** [comment]
How do you think we can fix this issue? The colours are always generated randomly. Even though we use `react.memo` the colours will be generated on the refresh. At the moment the first thing that comes to me is to save the colours of each user in the local storage of the browser, then when the page is reloaded he the app search for the saved colours and apply them. Do you have other ideia in mind?

**Comment by dvpfran** [comment]
I agree with the alternative of saving the colors of each user when the account is created.
