### ISSUE TITLE
[FEATURE]: Save stakeholders into `team_user` table

### ISSUE THREAD

**Issue by dsousa12** [xgeekshq/split#279]
## Summary

Instead save stakeholders inside a static JSON, save on a property inside `team_user` table.

### Notes

* Delete the stakeholders file;
* Update the stakeholders endpoint.

### Motivation

No need to manually update this file.

**Comment by geomarb** [comment]
Removed "/all" from "/boards/stakeholders/all" in the backend and in the frontend. Now both sides use GET /boards/stakeholders.
