### ISSUE TITLE
[FIX]: Board Settings switchs not working properly

### ISSUE THREAD

**Issue by dsousa12** [xgeekshq/split#282]
## Description

When you change the state of "Option to post cards anonymously" the "Limit votes" are checked too, and if you uncheck the "Limit votes" and "Option to post cards anonymously" the "Limit votes" are checked again.

### Steps to reproduce

1. Login in the app;
2. On Boards/Dashboard page access to a board;
3. Open Board Settings dialog;
4. Change status of "Option to post cards anonymously" and "Limit votes".

### Expected result

The status of switchs not change the other switch state.

### Actual result

When you change a state of "Option to post cards anonymously" the status of "Limit votes" change too.

**Comment by joaosantos99** [comment]
I can't reproduce your error
