### ISSUE TITLE
[FEATURE]: Swagger Documentation

### ISSUE THREAD

**Issue by dsousa12** [xgeekshq/split#296]
## Summary

Implementation of **Swagger** documentation.

### Notes

- [x] Install `swagger-ui-express` and `@nestjs/swagger`;
- [x] Add configurations on `main.ts`;
   > ```ts
   >const config = new DocumentBuilder()
   >    .setTitle('SPLIT')
   >    .setVersion('0.0.1')
   >    .build();
   >
   >  const document = SwaggerModule.createDocument(app, config);
   >
   >  SwaggerModule.setup('swagger', app, document);
   >```
- [x] Add params, body and summary decorators to:
   - [x] Auth Module
   - [x] Azure Module
   - [x] Boards Module
   - [x] Cards Module
   - [x] Comments Module
   - [x] Teams Module
   - [x] Users (only DTOs - <small>don't have controller</small>)
   - [x] Votes Module
 - [x] Set responses schemas and types:
   - [x] Auth Module
   - [x] Azure Module
   - [x] Boards Module
   - [x] Cards Module
   - [x] Comments Module
   - [x] Teams Module
   - [x] Votes Module
- [x] Add tags
   - Authentication;
   - Boards;
   - Teams;
   - Votes;
   - Comments;
- [x] Default Errors Responses
	- [x] **400** - Bad Request
	- [x] **401** - Unauthorized
	- [x] **403** - Forbidden
	- [x] **404** - Not Found
	- [x] **500** - Internal Server Error

### Motivation

With **Swagger** the new members and frontend developers can see which endpoints exists on backend, can test that endpoints and see the possible responses/status code.

**Comment by CatiaBarroco-xgeeks** [comment]
for me it seems really good, I agree with this implementation

**Comment by dsousa12** [comment]
## **Note:**

After [MVP](https://github.com/xgeekshq/split/milestone/1) it's necessary refactoring all **DTO's** to have separated **DTO's** to creation methods (without `_id`).
