### ISSUE TITLE
[FIX]: Missing upper case validation on register user

### ISSUE THREAD

**Issue by FranciscoGaspar** [xgeekshq/split#311]
## Description

We can create a user with all lower cases password, resulting in the login showing the following error:

![175A28CD-0247-4A3E-8486-A0545A6D639E](https://user-images.githubusercontent.com/43963399/177734949-07b4cc25-b4df-4350-bdf9-f26d02e29389.png)

### Steps to reproduce

1. Create a user with all lower cases password.
2. Try to login with the user.

## Expected result

The register of the user should validate the upper case rule.

### Actual result

The register proceed with success resulting on login failure.

**Comment by dsousa12** [comment]
To fix change the regex to:
```
^(?=.*[A-Z])(?=.*\d)(?=.*\W)[A-Za-z\d\W]{8,}$
```
> **File:** `schemaRegisterForm`

> Please change on backend too
