### ISSUE TITLE
[BUG]: Sub-team preview members shows everyone

### ISSUE THREAD

**Issue by joaosantos99** [xgeekshq/split#381]
## Description

On the dashboard or boards page, in the sub-team preview members its shows all the members of the team

![Screenshot 2022-07-28 at 10 45 01](https://user-images.githubusercontent.com/68588265/181476066-b8d56213-5ffe-4097-a25a-2538166010fa.png)

**Comment by dsousa12** [comment]
This issue is already solved (issue #351  - only waiting review [#367](https://github.com/xgeekshq/split/pull/367))
