### ISSUE TITLE
[BUG] Password underscore

### ISSUE THREAD

**Issue by miguel-felix1** [xgeekshq/split#481]
## Description
As a user I should be able to use my password that includes special characters

### Current behavior
Underscore is not being counted as a special character

![Image](https://user-images.githubusercontent.com/87712174/195582562-e961f658-55f9-4e98-9a9a-4bd1337044bf.png)

**Comment by nunocaseiro** [comment]
@all-contributors please add @miguel-felix1  for code, bug, review and userTesting
