### ISSUE TITLE
[BUG]: Board created is not persisting value of "slackEnable" option

### ISSUE THREAD

**Issue by mourabraz** [xgeekshq/split#519]
## Description

When a user creates a new board the option for slack is not being persisted. We need this value for the recurrent board.

### Expected result

The persisted data for the new board should have the slack option value ("slackEnable" property)

### Actual result

When the cron job recreates the recurrent board it hasn't the information if it should dispatch the current board to Slack communication service.

### Related to 
#157 
#50

**Comment by mourabraz** [comment]
## The data must be saved in the "schedule" document. At least for the MVP.

**Comment by nunocaseiro** [comment]
@all-contributors please add @mourabraz for code, documentation and review
