### ISSUE TITLE
[BUG]: Cannot click or select text when editing a card

### ISSUE THREAD

**Issue by dpompeu-xgeeks** [xgeekshq/split#989]
## Description

When editing a card, I can't change cursor position or select text with mouse.

### Steps to reproduce

- Create a card
- Start editing 
  - A: Try to select text
  - B: Click anywhere in the text

### Expected result

A: Text gets selected

B: Cursor moves to intended position

### Actual result

A: nothing happens (text not selected)

B: nothing happens (cursor stays at the end)

https://user-images.githubusercontent.com/78373402/216292141-43392723-c440-48fc-91e2-99fc822000c2.mp4

**Comment by nunocaseiro** [comment]
Which browser are you using?

**Comment by dpompeu-xgeeks** [comment]
Good point, I'm using firefox.

**Comment by nunocaseiro** [comment]
ahah nice, we should find out why is this happening with firefox
